server:
  port: 8081

spring:
  application:
    name: sportsLife
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/sportsLife?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      ##############连接池配置##################
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      validation-query: SELECT 1 FROM DUAL
      query-timeout: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filter:
        stat:
          db-type: mysql
      stat-view-servlet:
        login-username: admin
        login-password: 666666
        enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#mybatis 生成文件路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.sports.life.config.TypeHandler
swagger2:
  enable: true
#redis配置
redis:
  host: localhost
  port: 6379
  lettuce:
    pool:
      max-active: 1024
      max-wait: PT10S
      max-idle: 200
      min-idle: 0
    timeout: PT10S
#JWT
jwt:
  secretKey: 78944878877848fg)
  accessTokenExpireTime: PT2H
  refreshTokenExpireTime: PT8H
  refreshTokenExpireAppTime: P30D
  issuer: sportsLife.org.cn
#文件上传

wx:
  appid: wx1290745127138ab5
  secret: b8ede50211e83d618e6a110ff63d9def